/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Signature for utxo.
 */
@ApiModel(description = "Signature for utxo.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-03T16:43:19.203251+09:00[Asia/Tokyo]")
public class SensibleSignatureUtxo {
  public static final String SERIALIZED_NAME_TX_ID = "txId";
  @SerializedName(SERIALIZED_NAME_TX_ID)
  private String txId;

  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  private Integer index;

  public static final String SERIALIZED_NAME_SIG_B_E = "sigBE";
  @SerializedName(SERIALIZED_NAME_SIG_B_E)
  private String sigBE;

  public static final String SERIALIZED_NAME_SIG_L_E = "sigLE";
  @SerializedName(SERIALIZED_NAME_SIG_L_E)
  private String sigLE;

  public static final String SERIALIZED_NAME_PADDING = "padding";
  @SerializedName(SERIALIZED_NAME_PADDING)
  private String padding;

  public static final String SERIALIZED_NAME_PAYLOAD = "payload";
  @SerializedName(SERIALIZED_NAME_PAYLOAD)
  private String payload;


  public SensibleSignatureUtxo txId(String txId) {
    
    this.txId = txId;
    return this;
  }

   /**
   * Utxo txid.
   * @return txId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Utxo txid.")

  public String getTxId() {
    return txId;
  }


  public void setTxId(String txId) {
    this.txId = txId;
  }


  public SensibleSignatureUtxo index(Integer index) {
    
    this.index = index;
    return this;
  }

   /**
   * utxo index
   * @return index
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "utxo index")

  public Integer getIndex() {
    return index;
  }


  public void setIndex(Integer index) {
    this.index = index;
  }


  public SensibleSignatureUtxo sigBE(String sigBE) {
    
    this.sigBE = sigBE;
    return this;
  }

   /**
   * Big endian signature hex.
   * @return sigBE
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Big endian signature hex.")

  public String getSigBE() {
    return sigBE;
  }


  public void setSigBE(String sigBE) {
    this.sigBE = sigBE;
  }


  public SensibleSignatureUtxo sigLE(String sigLE) {
    
    this.sigLE = sigLE;
    return this;
  }

   /**
   * Little endian signature hex.
   * @return sigLE
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Little endian signature hex.")

  public String getSigLE() {
    return sigLE;
  }


  public void setSigLE(String sigLE) {
    this.sigLE = sigLE;
  }


  public SensibleSignatureUtxo padding(String padding) {
    
    this.padding = padding;
    return this;
  }

   /**
   * Signature padding.
   * @return padding
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Signature padding.")

  public String getPadding() {
    return padding;
  }


  public void setPadding(String padding) {
    this.padding = padding;
  }


  public SensibleSignatureUtxo payload(String payload) {
    
    this.payload = payload;
    return this;
  }

   /**
   * Signature payload(txid, index, value, hash160(script))
   * @return payload
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Signature payload(txid, index, value, hash160(script))")

  public String getPayload() {
    return payload;
  }


  public void setPayload(String payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SensibleSignatureUtxo sensibleSignatureUtxo = (SensibleSignatureUtxo) o;
    return Objects.equals(this.txId, sensibleSignatureUtxo.txId) &&
        Objects.equals(this.index, sensibleSignatureUtxo.index) &&
        Objects.equals(this.sigBE, sensibleSignatureUtxo.sigBE) &&
        Objects.equals(this.sigLE, sensibleSignatureUtxo.sigLE) &&
        Objects.equals(this.padding, sensibleSignatureUtxo.padding) &&
        Objects.equals(this.payload, sensibleSignatureUtxo.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txId, index, sigBE, sigLE, padding, payload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SensibleSignatureUtxo {\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    sigBE: ").append(toIndentedString(sigBE)).append("\n");
    sb.append("    sigLE: ").append(toIndentedString(sigLE)).append("\n");
    sb.append("    padding: ").append(toIndentedString(padding)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

