/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Sensible fungible token transaction history for specific address
 */
@ApiModel(description = "Sensible fungible token transaction history for specific address")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-03T16:43:19.203251+09:00[Asia/Tokyo]")
public class SensibleFtTransaction {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_CODE_HASH = "codeHash";
  @SerializedName(SERIALIZED_NAME_CODE_HASH)
  private String codeHash;

  public static final String SERIALIZED_NAME_GENESIS = "genesis";
  @SerializedName(SERIALIZED_NAME_GENESIS)
  private String genesis;

  public static final String SERIALIZED_NAME_SENSIBLE_ID = "sensibleId";
  @SerializedName(SERIALIZED_NAME_SENSIBLE_ID)
  private String sensibleId;

  public static final String SERIALIZED_NAME_TXID = "txid";
  @SerializedName(SERIALIZED_NAME_TXID)
  private String txid;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SYMBOL = "symbol";
  @SerializedName(SERIALIZED_NAME_SYMBOL)
  private String symbol;

  public static final String SERIALIZED_NAME_DECIMAL = "decimal";
  @SerializedName(SERIALIZED_NAME_DECIMAL)
  private Integer decimal;

  public static final String SERIALIZED_NAME_INCOME = "income";
  @SerializedName(SERIALIZED_NAME_INCOME)
  private Long income;

  public static final String SERIALIZED_NAME_OUTCOME = "outcome";
  @SerializedName(SERIALIZED_NAME_OUTCOME)
  private Long outcome;

  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  private Integer height;

  public static final String SERIALIZED_NAME_BLOCK_INDEX = "blockIndex";
  @SerializedName(SERIALIZED_NAME_BLOCK_INDEX)
  private Integer blockIndex;

  public static final String SERIALIZED_NAME_BLOCK_TIME = "blockTime";
  @SerializedName(SERIALIZED_NAME_BLOCK_TIME)
  private Long blockTime;

  public static final String SERIALIZED_NAME_FLAG = "flag";
  @SerializedName(SERIALIZED_NAME_FLAG)
  private String flag;


  public SensibleFtTransaction address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * The querying address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The querying address")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public SensibleFtTransaction codeHash(String codeHash) {
    
    this.codeHash = codeHash;
    return this;
  }

   /**
   * Codehash of the token.
   * @return codeHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Codehash of the token.")

  public String getCodeHash() {
    return codeHash;
  }


  public void setCodeHash(String codeHash) {
    this.codeHash = codeHash;
  }


  public SensibleFtTransaction genesis(String genesis) {
    
    this.genesis = genesis;
    return this;
  }

   /**
   * Genesis of the token.
   * @return genesis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Genesis of the token.")

  public String getGenesis() {
    return genesis;
  }


  public void setGenesis(String genesis) {
    this.genesis = genesis;
  }


  public SensibleFtTransaction sensibleId(String sensibleId) {
    
    this.sensibleId = sensibleId;
    return this;
  }

   /**
   * SensibleId of the token
   * @return sensibleId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SensibleId of the token")

  public String getSensibleId() {
    return sensibleId;
  }


  public void setSensibleId(String sensibleId) {
    this.sensibleId = sensibleId;
  }


  public SensibleFtTransaction txid(String txid) {
    
    this.txid = txid;
    return this;
  }

   /**
   * Txid for this transaction.
   * @return txid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Txid for this transaction.")

  public String getTxid() {
    return txid;
  }


  public void setTxid(String txid) {
    this.txid = txid;
  }


  public SensibleFtTransaction name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the token.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the token.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public SensibleFtTransaction symbol(String symbol) {
    
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol of the token.
   * @return symbol
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Symbol of the token.")

  public String getSymbol() {
    return symbol;
  }


  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }


  public SensibleFtTransaction decimal(Integer decimal) {
    
    this.decimal = decimal;
    return this;
  }

   /**
   * The decimal position.
   * @return decimal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The decimal position.")

  public Integer getDecimal() {
    return decimal;
  }


  public void setDecimal(Integer decimal) {
    this.decimal = decimal;
  }


  public SensibleFtTransaction income(Long income) {
    
    this.income = income;
    return this;
  }

   /**
   * Total received token(This token only)
   * @return income
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total received token(This token only)")

  public Long getIncome() {
    return income;
  }


  public void setIncome(Long income) {
    this.income = income;
  }


  public SensibleFtTransaction outcome(Long outcome) {
    
    this.outcome = outcome;
    return this;
  }

   /**
   * Total spent token(This token only)
   * @return outcome
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total spent token(This token only)")

  public Long getOutcome() {
    return outcome;
  }


  public void setOutcome(Long outcome) {
    this.outcome = outcome;
  }


  public SensibleFtTransaction height(Integer height) {
    
    this.height = height;
    return this;
  }

   /**
   * Height for this transaction. -1 for unconfirmed
   * @return height
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Height for this transaction. -1 for unconfirmed")

  public Integer getHeight() {
    return height;
  }


  public void setHeight(Integer height) {
    this.height = height;
  }


  public SensibleFtTransaction blockIndex(Integer blockIndex) {
    
    this.blockIndex = blockIndex;
    return this;
  }

   /**
   * Block index for this transaction, -1 for unconfirmed
   * @return blockIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Block index for this transaction, -1 for unconfirmed")

  public Integer getBlockIndex() {
    return blockIndex;
  }


  public void setBlockIndex(Integer blockIndex) {
    this.blockIndex = blockIndex;
  }


  public SensibleFtTransaction blockTime(Long blockTime) {
    
    this.blockTime = blockTime;
    return this;
  }

   /**
   * Block timestamp for this transaction, if unconfirmed, the time is first seen time.
   * @return blockTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Block timestamp for this transaction, if unconfirmed, the time is first seen time.")

  public Long getBlockTime() {
    return blockTime;
  }


  public void setBlockTime(Long blockTime) {
    this.blockTime = blockTime;
  }


  public SensibleFtTransaction flag(String flag) {
    
    this.flag = flag;
    return this;
  }

   /**
   * Paging flag, format blockTimestamp_blockIndex
   * @return flag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Paging flag, format blockTimestamp_blockIndex")

  public String getFlag() {
    return flag;
  }


  public void setFlag(String flag) {
    this.flag = flag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SensibleFtTransaction sensibleFtTransaction = (SensibleFtTransaction) o;
    return Objects.equals(this.address, sensibleFtTransaction.address) &&
        Objects.equals(this.codeHash, sensibleFtTransaction.codeHash) &&
        Objects.equals(this.genesis, sensibleFtTransaction.genesis) &&
        Objects.equals(this.sensibleId, sensibleFtTransaction.sensibleId) &&
        Objects.equals(this.txid, sensibleFtTransaction.txid) &&
        Objects.equals(this.name, sensibleFtTransaction.name) &&
        Objects.equals(this.symbol, sensibleFtTransaction.symbol) &&
        Objects.equals(this.decimal, sensibleFtTransaction.decimal) &&
        Objects.equals(this.income, sensibleFtTransaction.income) &&
        Objects.equals(this.outcome, sensibleFtTransaction.outcome) &&
        Objects.equals(this.height, sensibleFtTransaction.height) &&
        Objects.equals(this.blockIndex, sensibleFtTransaction.blockIndex) &&
        Objects.equals(this.blockTime, sensibleFtTransaction.blockTime) &&
        Objects.equals(this.flag, sensibleFtTransaction.flag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, codeHash, genesis, sensibleId, txid, name, symbol, decimal, income, outcome, height, blockIndex, blockTime, flag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SensibleFtTransaction {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    codeHash: ").append(toIndentedString(codeHash)).append("\n");
    sb.append("    genesis: ").append(toIndentedString(genesis)).append("\n");
    sb.append("    sensibleId: ").append(toIndentedString(sensibleId)).append("\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    decimal: ").append(toIndentedString(decimal)).append("\n");
    sb.append("    income: ").append(toIndentedString(income)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    blockIndex: ").append(toIndentedString(blockIndex)).append("\n");
    sb.append("    blockTime: ").append(toIndentedString(blockTime)).append("\n");
    sb.append("    flag: ").append(toIndentedString(flag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

