/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ClientPubkeyRequest
 */
public class ClientPubkeyRequestTest {
    private final ClientPubkeyRequest model = new ClientPubkeyRequest();

    /**
     * Model tests for ClientPubkeyRequest
     */
    @Test
    public void testClientPubkeyRequest() {
        // TODO: test ClientPubkeyRequest
    }

    /**
     * Test the property 'pubkey'
     */
    @Test
    public void pubkeyTest() {
        // TODO: test pubkey
    }

}
