/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.1.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SensibleNftAddressSummary
 */
public class SensibleNftAddressSummaryTest {
    private final SensibleNftAddressSummary model = new SensibleNftAddressSummary();

    /**
     * Model tests for SensibleNftAddressSummary
     */
    @Test
    public void testSensibleNftAddressSummary() {
        // TODO: test SensibleNftAddressSummary
    }

    /**
     * Test the property 'codeHash'
     */
    @Test
    public void codeHashTest() {
        // TODO: test codeHash
    }

    /**
     * Test the property 'genesis'
     */
    @Test
    public void genesisTest() {
        // TODO: test genesis
    }

    /**
     * Test the property 'sensibleId'
     */
    @Test
    public void sensibleIdTest() {
        // TODO: test sensibleId
    }

    /**
     * Test the property 'metaTxid'
     */
    @Test
    public void metaTxidTest() {
        // TODO: test metaTxid
    }

    /**
     * Test the property 'metaOutputIndex'
     */
    @Test
    public void metaOutputIndexTest() {
        // TODO: test metaOutputIndex
    }

    /**
     * Test the property 'tokenSupply'
     */
    @Test
    public void tokenSupplyTest() {
        // TODO: test tokenSupply
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

}
