/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.1.1
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SensibleFtBalance
 */
public class SensibleFtBalanceTest {
    private final SensibleFtBalance model = new SensibleFtBalance();

    /**
     * Model tests for SensibleFtBalance
     */
    @Test
    public void testSensibleFtBalance() {
        // TODO: test SensibleFtBalance
    }

    /**
     * Test the property 'codeHash'
     */
    @Test
    public void codeHashTest() {
        // TODO: test codeHash
    }

    /**
     * Test the property 'genesis'
     */
    @Test
    public void genesisTest() {
        // TODO: test genesis
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'decimal'
     */
    @Test
    public void decimalTest() {
        // TODO: test decimal
    }

    /**
     * Test the property 'sensibleId'
     */
    @Test
    public void sensibleIdTest() {
        // TODO: test sensibleId
    }

    /**
     * Test the property 'utxoCount'
     */
    @Test
    public void utxoCountTest() {
        // TODO: test utxoCount
    }

    /**
     * Test the property 'confirmed'
     */
    @Test
    public void confirmedTest() {
        // TODO: test confirmed
    }

    /**
     * Test the property 'confirmedString'
     */
    @Test
    public void confirmedStringTest() {
        // TODO: test confirmedString
    }

    /**
     * Test the property 'unconfirmed'
     */
    @Test
    public void unconfirmedTest() {
        // TODO: test unconfirmed
    }

    /**
     * Test the property 'unconfirmedString'
     */
    @Test
    public void unconfirmedStringTest() {
        // TODO: test unconfirmedString
    }

}
