/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.1.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SensibleNftSellV2Utxo
 */
public class SensibleNftSellV2UtxoTest {
    private final SensibleNftSellV2Utxo model = new SensibleNftSellV2Utxo();

    /**
     * Model tests for SensibleNftSellV2Utxo
     */
    @Test
    public void testSensibleNftSellV2Utxo() {
        // TODO: test SensibleNftSellV2Utxo
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'contractAddress'
     */
    @Test
    public void contractAddressTest() {
        // TODO: test contractAddress
    }

    /**
     * Test the property 'txid'
     */
    @Test
    public void txidTest() {
        // TODO: test txid
    }

    /**
     * Test the property 'txIndex'
     */
    @Test
    public void txIndexTest() {
        // TODO: test txIndex
    }

    /**
     * Test the property 'codeHash'
     */
    @Test
    public void codeHashTest() {
        // TODO: test codeHash
    }

    /**
     * Test the property 'genesis'
     */
    @Test
    public void genesisTest() {
        // TODO: test genesis
    }

    /**
     * Test the property 'tokenIndex'
     */
    @Test
    public void tokenIndexTest() {
        // TODO: test tokenIndex
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'feeAddressPkh'
     */
    @Test
    public void feeAddressPkhTest() {
        // TODO: test feeAddressPkh
    }

    /**
     * Test the property 'feeRate'
     */
    @Test
    public void feeRateTest() {
        // TODO: test feeRate
    }

    /**
     * Test the property 'nftId'
     */
    @Test
    public void nftIdTest() {
        // TODO: test nftId
    }

    /**
     * Test the property 'sellerAddressPkh'
     */
    @Test
    public void sellerAddressPkhTest() {
        // TODO: test sellerAddressPkh
    }

    /**
     * Test the property 'satoshi'
     */
    @Test
    public void satoshiTest() {
        // TODO: test satoshi
    }

    /**
     * Test the property 'satoshiString'
     */
    @Test
    public void satoshiStringTest() {
        // TODO: test satoshiString
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'isReady'
     */
    @Test
    public void isReadyTest() {
        // TODO: test isReady
    }

    /**
     * Test the property 'sensibleId'
     */
    @Test
    public void sensibleIdTest() {
        // TODO: test sensibleId
    }

    /**
     * Test the property 'metaTxid'
     */
    @Test
    public void metaTxidTest() {
        // TODO: test metaTxid
    }

    /**
     * Test the property 'metaOutputIndex'
     */
    @Test
    public void metaOutputIndexTest() {
        // TODO: test metaOutputIndex
    }

    /**
     * Test the property 'tokenSupply'
     */
    @Test
    public void tokenSupplyTest() {
        // TODO: test tokenSupply
    }

    /**
     * Test the property 'flag'
     */
    @Test
    public void flagTest() {
        // TODO: test flag
    }

}
