/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.1.1
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TxInput
 */
public class TxInputTest {
    private final TxInput model = new TxInput();

    /**
     * Model tests for TxInput
     */
    @Test
    public void testTxInput() {
        // TODO: test TxInput
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'utxoTxid'
     */
    @Test
    public void utxoTxidTest() {
        // TODO: test utxoTxid
    }

    /**
     * Test the property 'utxoIndex'
     */
    @Test
    public void utxoIndexTest() {
        // TODO: test utxoIndex
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'unlockScript'
     */
    @Test
    public void unlockScriptTest() {
        // TODO: test unlockScript
    }

}
