/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.1.1
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserHourlyTraffic
 */
public class UserHourlyTrafficTest {
    private final UserHourlyTraffic model = new UserHourlyTraffic();

    /**
     * Model tests for UserHourlyTraffic
     */
    @Test
    public void testUserHourlyTraffic() {
        // TODO: test UserHourlyTraffic
    }

    /**
     * Test the property 'hourTime'
     */
    @Test
    public void hourTimeTest() {
        // TODO: test hourTime
    }

    /**
     * Test the property 'hourTimeString'
     */
    @Test
    public void hourTimeStringTest() {
        // TODO: test hourTimeString
    }

    /**
     * Test the property 'totalBytes'
     */
    @Test
    public void totalBytesTest() {
        // TODO: test totalBytes
    }

}
