/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for XpubRequest
 */
public class XpubRequestTest {
    private final XpubRequest model = new XpubRequest();

    /**
     * Model tests for XpubRequest
     */
    @Test
    public void testXpubRequest() {
        // TODO: test XpubRequest
    }

    /**
     * Test the property 'xpub'
     */
    @Test
    public void xpubTest() {
        // TODO: test xpub
    }

    /**
     * Test the property 'skipHeight'
     */
    @Test
    public void skipHeightTest() {
        // TODO: test skipHeight
    }

    /**
     * Test the property 'initReceiveIndex'
     */
    @Test
    public void initReceiveIndexTest() {
        // TODO: test initReceiveIndex
    }

    /**
     * Test the property 'initChangeIndex'
     */
    @Test
    public void initChangeIndexTest() {
        // TODO: test initChangeIndex
    }

}
