/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.1.1
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for XpubDetail
 */
public class XpubDetailTest {
    private final XpubDetail model = new XpubDetail();

    /**
     * Model tests for XpubDetail
     */
    @Test
    public void testXpubDetail() {
        // TODO: test XpubDetail
    }

    /**
     * Test the property 'xpub'
     */
    @Test
    public void xpubTest() {
        // TODO: test xpub
    }

    /**
     * Test the property 'receiveIndex'
     */
    @Test
    public void receiveIndexTest() {
        // TODO: test receiveIndex
    }

    /**
     * Test the property 'maxReceiveIndex'
     */
    @Test
    public void maxReceiveIndexTest() {
        // TODO: test maxReceiveIndex
    }

    /**
     * Test the property 'changeIndex'
     */
    @Test
    public void changeIndexTest() {
        // TODO: test changeIndex
    }

    /**
     * Test the property 'maxChangeIndex'
     */
    @Test
    public void maxChangeIndexTest() {
        // TODO: test maxChangeIndex
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'skipHeight'
     */
    @Test
    public void skipHeightTest() {
        // TODO: test skipHeight
    }

    /**
     * Test the property 'processHeight'
     */
    @Test
    public void processHeightTest() {
        // TODO: test processHeight
    }

}
