/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for XPubTransaction
 */
public class XPubTransactionTest {
    private final XPubTransaction model = new XPubTransaction();

    /**
     * Model tests for XPubTransaction
     */
    @Test
    public void testXPubTransaction() {
        // TODO: test XPubTransaction
    }

    /**
     * Test the property 'xpub'
     */
    @Test
    public void xpubTest() {
        // TODO: test xpub
    }

    /**
     * Test the property 'txid'
     */
    @Test
    public void txidTest() {
        // TODO: test txid
    }

    /**
     * Test the property 'maxReceiveIndex'
     */
    @Test
    public void maxReceiveIndexTest() {
        // TODO: test maxReceiveIndex
    }

    /**
     * Test the property 'maxChangeIndex'
     */
    @Test
    public void maxChangeIndexTest() {
        // TODO: test maxChangeIndex
    }

    /**
     * Test the property 'income'
     */
    @Test
    public void incomeTest() {
        // TODO: test income
    }

    /**
     * Test the property 'outcome'
     */
    @Test
    public void outcomeTest() {
        // TODO: test outcome
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'blockIndex'
     */
    @Test
    public void blockIndexTest() {
        // TODO: test blockIndex
    }

    /**
     * Test the property 'blockTime'
     */
    @Test
    public void blockTimeTest() {
        // TODO: test blockTime
    }

    /**
     * Test the property 'flag'
     */
    @Test
    public void flagTest() {
        // TODO: test flag
    }

}
