/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.api;

import com.metasv.client.openapi.ApiException;
import com.metasv.client.openapi.model.AddressUtxo;
import com.metasv.client.openapi.model.BroadcastResult;
import com.metasv.client.openapi.model.TxRaw;
import com.metasv.client.openapi.model.UtxoPickRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MerchantApi
 */
@Ignore
public class MerchantApiTest {

    private final MerchantApi api = new MerchantApi();

    
    /**
     * Broadcast tx to coorperated miner merchant APIs(TAAL).
     *
     * This api will broadcast to taal, you can broadcast tx with fee rate 0.25 sat/b by this api
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void merchantBroadcastPostTest() throws ApiException {
        TxRaw txRaw = null;
        BroadcastResult response = api.merchantBroadcastPost(txRaw);

        // TODO: test validations
    }
    
    /**
     * Pick utxos by addresses and amount.
     *
     * Selects a set of Utxos with total value higher than the given amount from a given address list . In case of HD wallets, multiple addresses can be specified.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void merchantUtxoPostTest() throws ApiException {
        String confirmed = null;
        UtxoPickRequest utxoPickRequest = null;
        List<AddressUtxo> response = api.merchantUtxoPost(confirmed, utxoPickRequest);

        // TODO: test validations
    }
    
}
