/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.api;

import com.metasv.client.openapi.ApiException;
import com.metasv.client.openapi.model.SensibleFtBalance;
import com.metasv.client.openapi.model.SensibleFtTransaction;
import com.metasv.client.openapi.model.SensibleFtUtxo;
import com.metasv.client.openapi.model.SensibleOracleInfo;
import com.metasv.client.openapi.model.SensibleSignatureUtxo;
import com.metasv.client.openapi.model.SensibleSignatureUtxoSpendBy;
import com.metasv.client.openapi.model.SensibleSignatureUtxoSpendByUtxo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SensibleApi
 */
@Ignore
public class SensibleApiTest {

    private final SensibleApi api = new SensibleApi();

    
    /**
     * Get all sensible token balances for specific address.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sensibleFtAddressAddressBalanceGetTest() throws ApiException {
        String address = null;
        String codeHash = null;
        String genesis = null;
        List<SensibleFtBalance> response = api.sensibleFtAddressAddressBalanceGet(address, codeHash, genesis);

        // TODO: test validations
    }
    
    /**
     * Get all sensible token transaction history for specific address.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sensibleFtAddressAddressTxsGetTest() throws ApiException {
        String address = null;
        String codeHash = null;
        String genesis = null;
        String flag = null;
        List<SensibleFtTransaction> response = api.sensibleFtAddressAddressTxsGet(address, codeHash, genesis, flag);

        // TODO: test validations
    }
    
    /**
     * Get all sensible token utxos for specific address.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sensibleFtAddressAddressUtxoGetTest() throws ApiException {
        String address = null;
        String codeHash = null;
        String genesis = null;
        List<SensibleFtUtxo> response = api.sensibleFtAddressAddressUtxoGet(address, codeHash, genesis);

        // TODO: test validations
    }
    
    /**
     * Get metasv sensible oracle info.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sensibleOracleGetTest() throws ApiException {
        SensibleOracleInfo response = api.sensibleOracleGet();

        // TODO: test validations
    }
    
    /**
     * Get signature for utxo spend by transaction.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sensibleOracleUtxoSpendByTxidIndexByTxidGetTest() throws ApiException {
        String txid = null;
        Integer index = null;
        String byTxid = null;
        SensibleSignatureUtxoSpendBy response = api.sensibleOracleUtxoSpendByTxidIndexByTxidGet(txid, index, byTxid);

        // TODO: test validations
    }
    
    /**
     * Get signature for utxo spend by transaction.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sensibleOracleUtxoSpendByUtxoTxidIndexByTxidByTxIndexGetTest() throws ApiException {
        String txid = null;
        Integer index = null;
        String byTxid = null;
        Integer byTxIndex = null;
        SensibleSignatureUtxoSpendByUtxo response = api.sensibleOracleUtxoSpendByUtxoTxidIndexByTxidByTxIndexGet(txid, index, byTxid, byTxIndex);

        // TODO: test validations
    }
    
    /**
     * Get signature for utxo.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sensibleOracleUtxoTxidIndexGetTest() throws ApiException {
        String txid = null;
        Integer index = null;
        SensibleSignatureUtxo response = api.sensibleOracleUtxoTxidIndexGet(txid, index);

        // TODO: test validations
    }
    
}
