/*
 * MetaSV API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.client.openapi.api;

import com.metasv.client.openapi.ApiException;
import com.metasv.client.openapi.model.ClientPubkeyRequest;
import com.metasv.client.openapi.model.ClientPubkeyResult;
import com.metasv.client.openapi.model.UserHourlyTraffic;
import com.metasv.client.openapi.model.UserTrafficSum;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    
    /**
     * See https://github.com/metasv/metasv-client-signature for details. Get all trusted public keys.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userClientPubkeyGetTest() throws ApiException {
        List<String> response = api.userClientPubkeyGet();

        // TODO: test validations
    }
    
    /**
     * See https://github.com/metasv/metasv-client-signature for details. Register new client public key.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userClientPubkeyPostTest() throws ApiException {
        ClientPubkeyRequest clientPubkeyRequest = null;
        ClientPubkeyResult response = api.userClientPubkeyPost(clientPubkeyRequest);

        // TODO: test validations
    }
    
    /**
     * Delete a registered client public key.
     *
     * See https://github.com/metasv/metasv-client-signature for details. You can use this api to delete your registered public key.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userClientPubkeyPubkeyDeleteTest() throws ApiException {
        String pubkey = null;
        ClientPubkeyResult response = api.userClientPubkeyPubkeyDelete(pubkey);

        // TODO: test validations
    }
    
    /**
     * Get traffic details for every hour(valid in six months).
     *
     * Return hourly summed outbound traffic bytes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userTrafficGetTest() throws ApiException {
        Long startTime = null;
        Long endTime = null;
        List<UserHourlyTraffic> response = api.userTrafficGet(startTime, endTime);

        // TODO: test validations
    }
    
    /**
     * Sum all traffic in the current month.
     *
     * Return  summed outbound traffic bytes in current month.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void userTrafficSumGetTest() throws ApiException {
        UserTrafficSum response = api.userTrafficSumGet();

        // TODO: test validations
    }
    
}
